-- V2__seed_admin.sql
-- Default admin account (password: Admin@123) — change immediately in production!
-- NOTE: if you already ran this migration against an existing database before
-- this file was corrected, do NOT edit this file further — Flyway tracks a
-- checksum per migration and will fail on mismatch. Use V3 instead, as done
-- here, to fix already-applied data.
INSERT INTO users (name, email, password_hash, role)
VALUES ('Admin', 'admin@taskflow.com', '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LeVOoAuBLT6BUinHK', 'ADMIN')
ON DUPLICATE KEY UPDATE id = id;
